#!/bin/bash

set -e

TEMPLATE_DIR=${0%/*/*}/lib/node_modules/${0##*/}/template

if [ -z "$1" ]; then
  npx create-react-app --help | sed 's/create-react-app/create-react-dapp/'
  exit 1
fi

APP_NAME=$1

echo '**********    Welcome    **********'
echo '********** 1. CREATE OCEAN DAPP ' $@ ' ***'
echo
npx create-react-app $@
echo '********** DONE CREATING REACT APP ***********'
echo '**********************************************'
echo
echo '********** 2. CREATING Ocean DAPP LAYER ************'
echo

## Files from /
mv $TEMPLATE_DIR/.flowconfig  $APP_NAME/
mv $TEMPLATE_DIR/.npmignore  $APP_NAME/.gitignore
mv $TEMPLATE_DIR/.eslintrc  $APP_NAME/
mv $TEMPLATE_DIR/.nvmrc  $APP_NAME/
mv $TEMPLATE_DIR/.prettierignore $APP_NAME/
mv $TEMPLATE_DIR/.prettierrc $APP_NAME/
mv $TEMPLATE_DIR/.stylelintrc $APP_NAME/
mv $TEMPLATE_DIR/.travis $APP_NAME/
mv $TEMPLATE_DIR/cypress $APP_NAME/
mv $TEMPLATE_DIR/docker-compose $APP_NAME/
mv $TEMPLATE_DIR/library $APP_NAME/
mv $TEMPLATE_DIR/tsconfig $APP_NAME/

node $TEMPLATE_DIR/../scripts/merge_package.js $TEMPLATE_DIR/ `pwd`/$APP_NAME/
mv $APP_NAME/README.md $APP_NAME/REACT.md
mv $TEMPLATE_DIR/TEMPLATE.md  $APP_NAME/README.md

## Files from /dapp
mv $TEMPLATE_DIR/dapp $APP_NAME

## Files from /server
mv $TEMPLATE_DIR/server $APP_NAME

## Files from /scripts
mv $TEMPLATE_DIR/scripts $APP_NAME

## Files from /cypress
mv $TEMPLATE_DIR/cypress $APP_NAME

## Files from /client
rm -rf $APP_NAME/src
mv $TEMPLATE_DIR/client  $APP_NAME/client/

echo '********** DONE CREATING Ocean DAPP LAYER **********'
echo '**********************************************'
echo
echo '********** 3. INSTALLING DEPENDENCIES ********'

if hash yarn 2>/dev/null; then
  (cd $APP_NAME && yarn)
else
  (cd $APP_NAME && npm install)
fi

echo '********** DONE INSTALLING DEPENDENCIES ******'
echo '**********************************************'
echo
echo '********** QUICK START NEXT STEPS ************'
echo
echo 'cd ' $APP_NAME
echo 'npm install'
echo 'npm start'
echo
echo '********** Happy Building! ********************'
